name: Deploy static content to Pages

on:
  push:
    branches: ['main'] # Se va a disparar cada vez que hagas un push a la rama 'main'

# Permisos necesarios para que GitHub Actions pueda publicar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build
        env:
          VITE_FIREBASE_FIRESTORE_DATABASE_ID: "(default)"
        run: |
          npm run build
          cp dist/index.html dist/404.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Esta es la carpeta que Vite genera cuando hace el build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
